mesosphere/d2iq-daggers

mage/precommit/mage.go, mage/svu/mage.go
Allow customizing svu targets using env variables.
=> feat: Add configuration options to svu via env

.golangci.yml, dagger/logger/logger.go, dagger/options/container_customizer.go, dagger/precommit/dagger.go, dagger/precommit/options.go, dagger/svu/dagger.go, dagger/svu/options.go, mage/precommit/mage.go, mage/svu/mage.go, utils/hash.go
=> chore: add missing godocs

mage/precommit/mage.go
This is a workaround for the issue: https://github.com/dagger/dagger/issues/3192.
=> fix: Use verbose logging always to see precommit output.

mage/precommit/mage.go
Removed extra error check block from precommit
=> fix: remove unnecessary error check

.github/workflows/test.yaml, hack/mage, mage.go, magefile.go
=> feat: Introduce go tests

dagger/precommit/dagger.go, dagger/precommit/options.go, dagger/svu/dagger.go, dagger/svu/options.go, go.mod, go.sum, mage/goreleaser/build/mage.go, mage/goreleaser/build/option.go, mage/goreleaser/release/mage.go, mage/goreleaser/release/option.go, mage/precommit/mage.go, mage/svu/mage.go
Introduces `caarlos0/env`  to simplify config management
=> refactor: use caarlos0/env lib to read env configuration

.github/workflows/test.yaml, .gitignore, dagger/golang/dagger.go, dagger/golang/doc.go, dagger/golang/options.go, magefile.go
Introduces new dagger package to run golang command and use it internal targets
=> feat: introduce dagger/golang

dagger/githubcli/dagger.go, dagger/githubcli/options.go, dagger/golang/dagger.go, dagger/golang/options.go, dagger/precommit/dagger.go, dagger/precommit/options.go, dagger/svu/dagger.go, dagger/svu/options.go, daggers/config.go, daggers/doc.go, mage/goreleaser/build/mage.go, mage/goreleaser/build/option.go, mage/goreleaser/release/mage.go, mage/goreleaser/release/option.go, mage/precommit/mage.go, mage/svu/mage.go
Introduces generic functional configuration mechanism instead of package-specific types and config init boilerplate code without losing flexibility
=> refactor: extract Option type to daggers package

dagger/githubcli/dagger.go, dagger/golang/dagger.go, dagger/logger/doc.go, dagger/precommit/dagger.go, dagger/svu/dagger.go, daggers/logger.go, daggers/runtime.go, daggers/runtime_options.go, magefile.go
Extracts dagger client creation logic and bootstrap parameters to runtime struct.
Depends on #47
=> refactor: extract dagger.Connect to daggers.Runtime

.github/workflows/code-quality-pr-size-label.yaml
Introduce new workflow labels PR according it's size
=> ci: add PR size label workflow

catalog/goreleaser/build/mage.go, catalog/goreleaser/build/option.go, catalog/goreleaser/cli.go, catalog/goreleaser/cli/doc.go, catalog/goreleaser/doc.go, catalog/goreleaser/release/mage.go, catalog/goreleaser/release/option.go
The goal of this PR is to reduce the complexity of the goreleaser package
Breaking Change: configuration changes
Depends on #52
=> refactor!: simplify goreleaser

catalog/svu/dagger.go, catalog/svu/mage.go, catalog/svu/options.go
=> refactor: clean-up svu

catalog/precommit/dagger.go, catalog/precommit/mage.go
Fixes workaround we introduced one of the earlier PRs
Depends on #54
=> refactor: move PrecommitWithOptions to mage.go again

catalog/golang/dagger.go, catalog/golang/options.go
Introduces container customizers and  go mod cache options to golang 
Depends on #55
=> feat: add new config options to golang

catalog/githubcli/dagger.go, catalog/githubcli/options.go
Introduces container customizers , extra env variables and optional workdir mount options
Depends on #56
=> feat: add new config options to  github-cli

catalog/githubcli/dagger.go, catalog/golang/dagger.go, catalog/precommit/dagger.go, catalog/precommit/options.go, daggers/containers/customizer.go
Extracts loading map of env vars to the container as a container customizer
Depends on #58
=> refactor: extract env map setting to container customizer

daggers/containers/customizer.go
Introduces set of ContainerCustomizerFns to load host env variables to dagger containers
Depends on #59
=> feat: introduce customizers for configuring host env variables

go.mod, go.sum
=> build(deps): bump dagger version

daggers/containers/customizer.go, magefile.go
Adds GitHub authentication helpers as container customizers
=> feat: add Github auth helpers

daggers/runtime_options.go
Fixes chicken and egg dependency
=> fix: use fn to configure to avoid chicken egg dependency

daggers/containers/customizer.go
:point_up:  as described in title
=> fix: configure ssh socket and github token as well

.github/workflows/test.yaml, catalog/gotest/mage.go, magefile.go
Let's add go unit test to the catalog.
=> feat: Add gotest target to mage catalog

.github/workflows/pre-commit.yaml, .github/workflows/test.yaml, catalog/golang/options.go, go.mod, go.sum
=> feat: Go 1.21 as default

.github/dependabot.yml
=> ci: Enable dependabot for GHA
